el_platform/urls.py
from django.urls import path
from .views import index, my_courses, create_course, delete_course, see_course, edit_course, add_stage, del_stage, join_course, finish_course

urlpatterns = [
   path("", index, name='home'),
   path("mycourses/",my_courses, name="mycourses" ),
   path("create_course/", create_course, name="createcourse"),
   path("delete_course/<int:id>", delete_course, name="delete"),
   path('course/<int:id>', see_course, name="show"),
   path("edit_course/<int:id>", edit_course, name="edit"),
   path("add_stage/<int:id>", add_stage, name="addstage" ),
   path("delete_stage/<int:id>", del_stage, name="deletestage"),
   path("join_course/<int:id>", join_course, name="join"),
   path("finish_course/<int:id>", finish_course, name="finish" ),
  
]

elearning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path("", include('el_platform.urls')),
    path("forum/", include("forum.urls"))
]

forum/urls.py
from django.urls import path
from .views import forum, add_post, delete_post, see_post, add_comment, delete_comment

urlpatterns = [
    path("", forum, name="forum" ),
    path("see_post/<int:id>", see_post, name="post"),
    path("add_post/", add_post, name="addpost"),
    path("delete_post/<int:id>", delete_post, name="deletepost"),
    #path("edit_post/<int:id>", edit_post, name="editpost"),
    path("add_comment/<int:id>", add_comment, name="addcomment"),
    path("delete_comment/<int:id>", delete_comment, name="deletecomment"),
   
]

el_platform/models.py
from django.db import models
from users.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name




class Course(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    #users = models.ManyToManyField(to='users.User', related_name="mycourses", blank=True)


class Stage(models.Model):
    title = models.CharField(max_length=100)
    video = models.URLField()
    text = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)


class Status(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    finished = models.BooleanField(default=False)
    

el_platform/forms.py
from django import forms
from .models import Course, Stage

class AddCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ("name", "description", "category",)


class AddStageForm(forms.ModelForm):
    class Meta:
        model = Stage
        fields = ("title", "video", "text",)

el_platform/views.py
from django.shortcuts import render, redirect
from .models import Course,Category, Stage, Status
from .forms import AddCourseForm, AddStageForm

# Create your views here.

def index(request):
    courses = Course.objects.all()
    categories = Category.objects.all()
    return render(request, "el_platform/show_all.html" ,{"items": courses, "categories": categories})



def my_courses(request):
    if request.user.is_authenticated:
       my_courses = request.user.courses.filter(user=request.user)
       return render(request, "el_platform/my_courses.html", {"courses": my_courses})
    return redirect("/auth/login")


def create_course(request):
    if request.user.is_authenticated:
        if request.user.has_perm("el_platform.add_course"):
            if request.method == "POST":
                form = AddCourseForm(request.POST)
                if form.is_valid():
                    data = form.cleaned_data
                    course = Course.objects.create(name=data["name"], description=data["description"], category=data["category"])
                    status = Status(user=request.user, course=course)
                    status.save()
                    course.save()
    
                    request.user.courses.add(course.id)
                    
                    
        form = AddCourseForm
        return render(request, "el_platform/create_course.html", {"form": form})
    return redirect("/auth/login")


def delete_course(request,id):
    if request.user.is_authenticated:
        if request.user.has_perm("el_platform.delete_course"):
            course = Course.objects.filter(pk=id)
            if course is not None:
                course.delete()
                return redirect("/")
    return redirect("/auth/login")


def see_course(request,id):
    course = Course.objects.filter(pk=id)
    stages = Stage.objects.filter(course=course[0])
    #print(course.values())
    if request.user.is_authenticated:
        joined = request.user.courses.filter(user=request.user, id=course[0].id)
        #print(joined)
        if len(joined) != 0:
            finished = Status.objects.filter(user=request.user.id, course=course[0])
            return render(request, "el_platform/course.html", {"course": course[0], "stages": stages, "joined": True, "finished":finished[0].finished})

    
    return render(request, "el_platform/course.html", {"course": course[0], "stages": stages})


def edit_course(request, id):
    if request.user.is_authenticated:
        if request.user.has_perm("el_platform.change_course"):
            course = Course.objects.filter(pk=id)[0]
            if request.method == "POST":
                form = AddCourseForm(request.POST)
                if form.is_valid():
                    data = form.cleaned_data
                    course.name = data["name"]
                    course.description = data["description"]
                    course.category = data["category"]
                    course.save()
                    return redirect("mycourses")
            
            form = AddCourseForm(instance=course)
            return render(request, "el_platform/edit_course.html", {"form": form})
    return redirect("/auth/login")




def add_stage(request, id):
    if request.user.is_authenticated:

        if request.user.has_perm("el_platform.add_stage"):
            if request.method == "POST":
                form = AddStageForm(request.POST)
                if form.is_valid():
                    course = Course.objects.filter(pk=id)
                    data = form.cleaned_data
                    stage = Stage.objects.create(title=data['title'], video=data['video'], text=data['text'], course=course[0])
                    #stage.course = course
    
    
            form = AddStageForm
            return render(request, "el_platform/add_stage.html", {"form": form})
    return redirect("/auth/login")
    


def del_stage(request, id):
    if request.user.is_authenticated:
        if request.user.has_perm("el_platform.delete_stage"):
            Stage.objects.filter(pk=id).delete()
            return redirect("home")
    return redirect("/auth/login")


def join_course(request, id):
    if request.user.is_authenticated:
        course = Course.objects.get(pk=id)
        request.user.courses.add(course.id)
        status = Status(user=request.user,course=course)
        status.save()
        return redirect("mycourses")
    return redirect("/auth/login")
    
def finish_course(request, id):
    if request.user.is_authenticated:
        #course = request.users.courses.filter(user=request.user.id, course=id)
        status = Status.objects.filter(user=request.user.id, course=id)[0]
        status.finished = True
        status.save()
        return redirect("mycourses") 
    return redirect("/auth/login")

el_platform/templates/el_platform/add_stage.html
{% extends "el_platform/index.html" %}


{% block body %}

<h1>Add Stage:</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" class="btn btn-success">
</form>



{% endblock body %}

el_platform/templates/el_platform/course.html
{% extends "el_platform/index.html" %}


{% block body %}
<img src="https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg" style="height: 250px; width: 250px;">

{% if perms.el_platform.change_course %}
    
    <a href="/delete_course/{{ course.id }}"><button class="btn btn-danger">Delete</button></a>
    {% if finished is not True%}
    <a href="/edit_course/{{ course.id }}"><button class="btn btn-warning">Edit</button></a>
    <a href="/finish_course/{{ course.id }}"><button class="btn btn-success">Finish</button></a>
    {% else %}
    <button class="btn btn-success">Already Finished</button>
    {% endif %}
    


{% elif joined %}
    
    {% if finished is not True%}
    <button class="btn btn-success">Already joined</button>
    <a href="/finish_course/{{ course.id }}"><button class="btn btn-success">Finish</button></a>
    {% else %}
    <button class="btn btn-success">Already Finished</button>
    {% endif %}

{% else %}
    <a href="/join_course/{{ course.id }}"><button class="btn btn-success">Join</button></a>

{% endif %}

<h1>{{ course.name }}</h1>
<h2>Category: {{ course.category }}</h2>
<p>Description: <br> {{ course.description }}</p>

<h1>Stages:</h1>

{% if perms.el_platform.change_stage and finished is not True%}
<a href="/add_stage/{{ course.id }}"><button class="btn btn-success">Add Stage</button></a>
{% endif %}

{% for stage in stages%}
<h1>{{ stage.title }}</h1>
{% if perms.el_platform.change_stage and perms.el_platform.delete_stage%}
<a href="/edit_stage/{{ stage.id }}"><button class="btn btn-warning">Edit</button></a>
<a href="/delete_stage/{{ stage.id }}"><button class="btn btn-danger">Delete</button></a>


{% endif %}

<iframe src="{{ stage.video }}" ></iframe>

<p>{{ stage.text }}</p>

{% endfor %}



{% endblock body %}

el_platform/templates/el_platform/create_course.html
{% extends "el_platform/index.html" %}



{% block body %}

<h1>Create Course:</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Create course">
</form>


{% endblock body %}

el_platform/templates/el_platform/edit_course.html
{% extends "el_platform/index.html" %}


{% block body %}

<h1>Edit:</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Edit" class="btn btn-warning">
</form>



{% endblock body %}

el_platform/templates/el_platform/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                <ul class="dropdown-menu">
                  {% for category in categories %}
                  <li><a class="dropdown-item" href="#">{{ category.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/mycourses/">My Courses</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/forum/">Forum</a>
                  </li>
                  {% if perms.el_platform.add_course%}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/create_course">Create</a>
                  </li>
                  {% endif %}
              {% endif %}
             
            </ul>

            {% if user.is_authenticated %}

            <p style="text-align: center;margin-right: 20px;">Logged In as {{ user.username }}<br>{{ user.role}}</p>
            
            <a href="/auth/logout"><button class="btn btn-primary">Log Out</button></a>

            {% else %}
               <a href="/auth/login"><button class="btn btn-primary">Log In</button></a>
               <a href="/auth/signup"><button class="btn btn-secondary">Sign Up</button></a>
            {% endif %}
          </div>
        </div>
      </nav>

    {% block body %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

el_platform/templates/el_platform/my_courses.html
{% extends "el_platform/index.html" %}


{% block body %}

{% for course in courses %}
<div class="card" style="width: 18rem; display: inline-block;">
    <img src="https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ course.name }}</h5>
      <p class="card-text">{{ course.description }}</p>
      <a href="/course/{{ course.id }}" class="btn btn-primary">See More</a>
    </div>
</div>

{% endfor %}



{% endblock body %}

el_platform/templates/el_platform/show_all.html
{% extends "el_platform/index.html" %}


{% block body %}

{% for item in items %}
<div class="card" style="width: 18rem; display:inline-block;">
    <img src="https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ item.name }}</h5>
      <p class="card-text">{{ item.description }}</p>
      <a href="/course/{{ item.id }}" class="btn btn-primary">See More</a>
    </div>
</div>

{% endfor %}


{% endblock body %}